### ISSUE TITLE
demo is using unreleased make-api

### ISSUE THREAD

**Issue by jaimesangcap** [green-coder/girouette#54]
Hi Vincent, thank you for making this great tool. 

Maybe this is more of a question. In the demo, the `make-api` accepts two arguments https://github.com/green-coder/girouette/blob/master/example/reagent-demo/src/acme/frontend/my_grammar.cljc#L71.

However, looks like that api change has not been released yet. 
Is there a workaround to add custom color in v0.0.2?

**Comment by green-coder** [comment]
I will try to realize v0.0.3 this weekend.

**Comment by green-coder** [comment]
Side note: the demo is always using Girouette from the git repository:

https://github.com/green-coder/girouette/blob/master/example/reagent-demo/deps.edn#L6
