### ISSUE TITLE
similar: https://www.npmjs.com/package/@tailwindcss/jit

### ISSUE THREAD

**Issue by awb99** [green-coder/girouette#69]
https://www.npmjs.com/package/@tailwindcss/jit

this project creates tailwind css file based on used classes.
so in a way very similarto girouette.
perhaps something to learn from for a point when girouette will ship a similar feature.

:-)

**Comment by oxalorg** [comment]
Girouette is already JIT, long before tailwind-jit came along :wink:

**Comment by green-coder** [comment]
@awb99 Thanks for the link. As Oxalorg said, Girouette was created way before Tailwind JIT. The author of Tailwind should have given proper credit to Girouette and WindiCSS for the ideas he copied, but unfortunately he chose not to and mislead his community into thinking that the ideas were from himself by being vague about their origin.

Timeline:
- First public commit of Girouette, December 28th 2020.
  https://github.com/green-coder/girouette/commit/ed704d60ef946af2c06e2054d013922ada3bd483
- Public presentation of Girouette, where I explain the ideas and how it works, January 13th 2021
  https://www.youtube.com/watch?v=Tnv6SvZM6tg
  I shared the link to this presentation to the author of Tailwind.
- Public announcement of Tailwind JIT, March 26th 2021.
   https://twitter.com/adamwathan/status/1371505992840663051

If you look at the timeline of WindiCSS, you will also find that we was made public way before Tailwind JIT.
