### ISSUE TITLE
Dark mode variant does not work for text

### ISSUE THREAD

**Issue by joe-loco** [green-coder/girouette#71]
I added a test case (see https://github.com/joe-loco/girouette/commit/41acf0e73ae46940d138aa8d94bee38ea71b94c6) that shows dark mode being correctly applied for backgrounds but not for text. Looking at the generated stylesheet, it seems selectors are sorted alphabetically with the dark-mode media queries coming before the `.text-` classes. I would assume outputting the media queries last should fix this.

**Comment by green-coder** [comment]
Thanks for the report, I will look into it tonight after work.
