### ISSUE TITLE
Tailwind max-width classes only partially supported

### ISSUE THREAD

**Issue by joe-loco** [green-coder/girouette#72]
Official Tailwind selectors for setting max-width, like `max-w-4xl` are simply ignored. Unofficial ones, like `max-w-50%`, seem to work fine though.

**Comment by joe-loco** [comment]
I added a bunch of more sizing tests for this in https://github.com/joe-loco/girouette/commit/57d512cd880d01017d7ee7a6a68d451a8a0d76d6. 

Also linking the Tailwind docs here for reference: https://tailwindcss.com/docs/max-width

**Comment by green-coder** [comment]
Thank you for the bug report 👍
