### ISSUE TITLE
README a bit outdated

### ISSUE THREAD

**Issue by fjolne** [green-coder/girouette#78]
> CSS libraries like Tailwind and Tachyons provide quantities of predefined class names, hoping to cover most of the needs of their users. But because of combinatory explosion, they cannot provide all the class names users will ever need, in which case the users will have to hack their way with config files and/or handwritten CSS. When releasing for production, the unused CSS classes are removed from the CSS files using tools like PurgeCSS.

Just to be factually correct, Tailwind supports “on-demand” class generation (which it calls JIT) since [v2](https://v2.tailwindcss.com/docs/just-in-time-mode) , and since [v3](https://tailwindcss.com/docs/upgrade-guide#migrating-to-the-jit-engine) it’s the default method.

**Comment by green-coder** [comment]
To be factually correct, one has to include the [`timeline of the README.md file`](https://github.com/green-coder/girouette/blame/master/README.md) in the comparison. The paragraph you quoted is from [`Jan 9, 2021`](https://github.com/green-coder/girouette/commit/da3f581d365b18babff20b90f05c60d14be243a6) at which point Tailwind did not have any JIT.

You are right that to point that it is no longer the case, I will update the text at some point.
