### ISSUE TITLE
Add "borders" class names in the grammar

### ISSUE THREAD

**Issue by green-coder** [green-coder/girouette#8]
The class names should at least be compatible with the ones used by Tailwind CSS.

**Comment by raphaelsaunier** [comment]
@green-coder shall I take a stab at this in the coming days or have you already started working on it? If not, have you identified any pitfalls with this set of classes?

**Comment by green-coder** [comment]
@raphaelsaunier Hi Raphael. I am not working on it yet, you are welcome to give it a try.

Note: For https://tailwindcss.com/docs/divide-width, I would like to get rid of `divide-y-reverse` and `divide-y-reverse`, similarly to what I did with `https://tailwindcss.com/docs/space`.

If it looks too difficult for a start, you may also want to try the other easier issues which I just tagged with the label `good-first-issue`.

**Comment by raphaelsaunier** [comment]
Excellent! Happy to take on the challenge over the week-end if you're not in a hurry to get it closed. I submitted a draft PR if you want to chime in.
