### ISSUE TITLE
Add Tailwind's v3 colors

### ISSUE THREAD

**Issue by green-coder** [green-coder/girouette#88]
We need a new list of colors beside `girouette.tw.color/default-color-map` representing the default colors of Tailwind v3.

**Comment by debaghosh** [comment]
You mean replacing the Tailwind v2 colors in default-color-map with the [v3 colors](https://tailwindcss.com/docs/customizing-colors#default-color-palette)?

**Comment by green-coder** [comment]
> You mean replacing the Tailwind v2 colors in default-color-map with the [v3 colors](https://tailwindcss.com/docs/customizing-colors#default-color-palette)?

I mean to add a separate list.
