### ISSUE TITLE
Any way to output colors without css vars? (or maybe as hex or rgb)

### ISSUE THREAD

**Issue by GetBitOutdoors** [green-coder/girouette#89]
I am trying to use Girouette + Ornament for email html generation, and the email clients are retrograde and have spotty support for newer CSS features like RGBA or CSS vars.

This is in the context of an ornament build, but it is only happening on Girouette tokens...

`(defstyled :div :text-black`
leads to these color rules in style tag
`--gi-text-opacity:1;color:rgba(255,255,255,var(--gi-text-opacity))`

Option to render to 6digit hex is the most bulletproof for email, but obviously that doesn't account for transparency in abstraction...

I noticed your new Tailwind 3 color spec has hex values. But the current clojars releas does not include this. I tried using a deps.edn git dependency, but the project does not seem to be structured to support that.

**Comment by green-coder** [comment]
Alternatively to `:text-black`, you can use `:text-rgb-000f` or `:text-#000f`

There are some tests that you can look at here:
- https://github.com/green-coder/girouette/blob/d36f1cb6e1d8ab502147f84882e55b51e8023b8e/lib/girouette/test/girouette/tw/typography_test.cljc#L125-L129
- https://github.com/green-coder/girouette/blob/d36f1cb6e1d8ab502147f84882e55b51e8023b8e/lib/girouette/test/girouette/tw/typography_test.cljc#L135-L139

Let me know if you still have a problem.

**Comment by green-coder** [comment]
No feedback from the OP, closing the issue.

**Comment by GetBitOutdoors** [comment]
Thanks for the option. This partially solves the issue. As I can generate those hex keywords from some higher level function. Might defeat the purpose of the succintness of tokens though.
